services:
  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"

  backend:
    env_file:
      - .env.test
    depends_on:
      mailpit:
        condition: service_started
