<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AngleSharp" />
      <PackageReference Include="AspNetCore.HealthChecks.NpgSql" />
      <PackageReference Include="AspNetCore.HealthChecks.UI.Client" />
      <PackageReference Include="BCrypt.Net-Next" />
      <PackageReference Include="EFCore.NamingConventions" />
      <PackageReference Include="FluentValidation" />
      <PackageReference Include="Google.Apis.Auth" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
      <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
      <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
      <PackageReference Include="Microsoft.IdentityModel.Tokens" />
      <PackageReference Include="Minio" />
      <PackageReference Include="Minio.AspNetCore.HealthChecks" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
      <PackageReference Include="QRCoder" />
      <PackageReference Include="Scalar.AspNetCore" />
      <PackageReference Include="Scrutor" />
      <PackageReference Include="Serilog.AspNetCore" />
      <PackageReference Include="Serilog.Expressions" />
      <PackageReference Include="ZiggyCreatures.FusionCache" />
    </ItemGroup>

</Project>
