// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Wishapp.Web.Infrastructure.Database;

#nullable disable

namespace Wishapp.Web.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260606105932_RemoveSystemWishlistType")]
    partial class RemoveSystemWishlistType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wishapp.Web.Admin.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_admin_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_admin_users_username");

                    b.ToTable("admin_users", "admin");
                });

            modelBuilder.Entity("Wishapp.Web.Catalog.Entities.CatalogCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.HasKey("Id")
                        .HasName("pk_catalog_categories");

                    b.HasIndex("IsPublished")
                        .HasDatabaseName("ix_catalog_categories_is_published");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_catalog_categories_name");

                    b.HasIndex("Order")
                        .HasDatabaseName("ix_catalog_categories_order");

                    b.ToTable("catalog_categories", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_catalog_categories_name_not_empty", "trim(name) <> ''");

                            t.HasCheckConstraint("CK_catalog_categories_order_non_negative", "\"order\" >= 0");
                        });
                });

            modelBuilder.Entity("Wishapp.Web.Catalog.Entities.CatalogCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CoverImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("cover_image_path");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("OccasionId")
                        .HasColumnType("uuid")
                        .HasColumnName("occasion_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.HasKey("Id")
                        .HasName("pk_catalog_collections");

                    b.HasIndex("IsPublished")
                        .HasDatabaseName("ix_catalog_collections_is_published");

                    b.HasIndex("OccasionId")
                        .HasDatabaseName("ix_catalog_collections_occasion_id");

                    b.HasIndex("Order")
                        .HasDatabaseName("ix_catalog_collections_order");

                    b.ToTable("catalog_collections", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_catalog_collections_name_not_empty", "trim(name) <> ''");

                            t.HasCheckConstraint("CK_catalog_collections_order_non_negative", "\"order\" >= 0");
                        });
                });

            modelBuilder.Entity("Wishapp.Web.Catalog.Entities.CatalogCollectionItem", b =>
                {
                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<Guid>("CatalogItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_item_id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("CollectionId", "CatalogItemId")
                        .HasName("pk_catalog_collection_items");

                    b.HasIndex("CatalogItemId")
                        .HasDatabaseName("ix_catalog_collection_items_catalog_item_id");

                    b.ToTable("catalog_collection_items", "catalog");
                });

            modelBuilder.Entity("Wishapp.Web.Catalog.Entities.CatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("to_tsvector('russian', coalesce(name, '') || ' ' || coalesce(description, ''))", true);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<int>("WishCount")
                        .HasColumnType("integer")
                        .HasColumnName("wish_count");

                    b.HasKey("Id")
                        .HasName("pk_catalog_items");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_catalog_items_category_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_catalog_items_created_at");

                    b.HasIndex("IsPublished")
                        .HasDatabaseName("ix_catalog_items_is_published");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_catalog_items_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "gin");

                    b.HasIndex("WishCount")
                        .HasDatabaseName("ix_catalog_items_wish_count");

                    b.ToTable("catalog_items", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_catalog_items_name_not_empty", "trim(name) <> ''");

                            t.HasCheckConstraint("CK_catalog_items_price_positive", "price > 0");
                        });
                });

            modelBuilder.Entity("Wishapp.Web.Catalog.Entities.CatalogItemOccasion", b =>
                {
                    b.Property<Guid>("CatalogItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_item_id");

                    b.Property<Guid>("OccasionId")
                        .HasColumnType("uuid")
                        .HasColumnName("occasion_id");

                    b.HasKey("CatalogItemId", "OccasionId")
                        .HasName("pk_catalog_item_occasions");

                    b.HasIndex("OccasionId")
                        .HasDatabaseName("ix_catalog_item_occasions_occasion_id");

                    b.ToTable("catalog_item_occasions", "catalog");
                });

            modelBuilder.Entity("Wishapp.Web.Catalog.Entities.CatalogOccasion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.HasKey("Id")
                        .HasName("pk_catalog_occasions");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_catalog_occasions_key");

                    b.HasIndex("Order")
                        .HasDatabaseName("ix_catalog_occasions_order");

                    b.ToTable("catalog_occasions", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_catalog_occasions_key_not_empty", "trim(key) <> ''");

                            t.HasCheckConstraint("CK_catalog_occasions_label_not_empty", "trim(label) <> ''");
                        });
                });

            modelBuilder.Entity("Wishapp.Web.Events.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("LinkedWishlistId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_wishlist_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_events_owner_id");

                    b.HasIndex("OwnerId", "Date")
                        .HasDatabaseName("ix_events_owner_id_date");

                    b.ToTable("events", "events", t =>
                        {
                            t.HasCheckConstraint("CK_events_title_not_empty", "trim(title) <> ''");
                        });
                });

            modelBuilder.Entity("Wishapp.Web.Friendships.Entities.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AddresseeId")
                        .HasColumnType("uuid")
                        .HasColumnName("addressee_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_friendships");

                    b.HasIndex("AddresseeId", "Status")
                        .HasDatabaseName("ix_friendships_addressee_id_status");

                    b.HasIndex("RequesterId", "AddresseeId")
                        .IsUnique()
                        .HasDatabaseName("ix_friendships_requester_id_addressee_id");

                    b.HasIndex("RequesterId", "Status")
                        .HasDatabaseName("ix_friendships_requester_id_status");

                    b.ToTable("friendships", "friendships", t =>
                        {
                            t.HasCheckConstraint("CK_friendships_no_self", "requester_id <> addressee_id");
                        });
                });

            modelBuilder.Entity("Wishapp.Web.Gamification.Entities.AchievementDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("text")
                        .HasColumnName("emoji");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("LinkedBadgeTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("linked_badge_type_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<int>("RuleType")
                        .HasColumnType("integer")
                        .HasColumnName("rule_type");

                    b.Property<int>("Threshold")
                        .HasColumnType("integer")
                        .HasColumnName("threshold");

                    b.HasKey("Id")
                        .HasName("pk_achievement_definitions");

                    b.ToTable("achievement_definitions", "gamification");
                });

            modelBuilder.Entity("Wishapp.Web.Gamification.Entities.CatalogBadgeDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("text")
                        .HasColumnName("emoji");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_catalog_badge_definitions");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_catalog_badge_definitions_slug");

                    b.ToTable("catalog_badge_definitions", "gamification");
                });

            modelBuilder.Entity("Wishapp.Web.Gamification.Entities.CatalogItemBadgeVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BadgeType")
                        .HasColumnType("integer")
                        .HasColumnName("badge_type");

                    b.Property<Guid>("CatalogItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_item_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_catalog_item_badge_votes");

                    b.HasIndex("CatalogItemId")
                        .HasDatabaseName("ix_catalog_item_badge_votes_catalog_item_id");

                    b.HasIndex("CatalogItemId", "UserId", "BadgeType")
                        .IsUnique()
                        .HasDatabaseName("ix_catalog_item_badge_votes_catalog_item_id_user_id_badge_type");

                    b.ToTable("catalog_item_badge_votes", "gamification");
                });

            modelBuilder.Entity("Wishapp.Web.Gamification.Entities.FulfilledWishBadge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BadgeType")
                        .HasColumnType("integer")
                        .HasColumnName("badge_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GifterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("gifter_user_id");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_user_id");

                    b.Property<Guid>("WishId")
                        .HasColumnType("uuid")
                        .HasColumnName("wish_id");

                    b.HasKey("Id")
                        .HasName("pk_fulfilled_wish_badges");

                    b.HasIndex("GifterUserId")
                        .HasDatabaseName("ix_fulfilled_wish_badges_gifter_user_id");

                    b.HasIndex("WishId")
                        .HasDatabaseName("ix_fulfilled_wish_badges_wish_id");

                    b.HasIndex("WishId", "BadgeType")
                        .IsUnique()
                        .HasDatabaseName("ix_fulfilled_wish_badges_wish_id_badge_type");

                    b.ToTable("fulfilled_wish_badges", "gamification");
                });

            modelBuilder.Entity("Wishapp.Web.Gamification.Entities.FulfilledWishBadgeDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("text")
                        .HasColumnName("emoji");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_fulfilled_wish_badge_definitions");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_fulfilled_wish_badge_definitions_slug");

                    b.ToTable("fulfilled_wish_badge_definitions", "gamification");
                });

            modelBuilder.Entity("Wishapp.Web.Gamification.Entities.UserAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DefinitionId")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("EarnedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("earned_at");

                    b.Property<bool>("IsEarned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_earned");

                    b.Property<int>("Progress")
                        .HasColumnType("integer")
                        .HasColumnName("progress");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_achievements");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_achievements_user_id");

                    b.HasIndex("UserId", "DefinitionId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_achievements_user_id_type");

                    b.ToTable("user_achievements", "gamification");
                });

            modelBuilder.Entity("Wishapp.Web.Notifications.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<JsonElement>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId", "IsRead", "CreatedAt")
                        .HasDatabaseName("ix_notifications_user_id_is_read_created_at");

                    b.ToTable("notifications", "notifications");
                });

            modelBuilder.Entity("Wishapp.Web.Proposals.Entities.GiftProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CatalogItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_item_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("custom_description");

                    b.Property<string>("CustomImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("custom_image_path");

                    b.Property<string>("CustomTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("custom_title");

                    b.Property<string>("HintMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("hint_message");

                    b.Property<bool>("IsViewedByRecipient")
                        .HasColumnType("boolean")
                        .HasColumnName("is_viewed_by_recipient");

                    b.Property<DateTimeOffset?>("ReactedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reacted_at");

                    b.Property<string>("RecipientComment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("recipient_comment");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_id");

                    b.Property<string>("SenderAlias")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sender_alias");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer")
                        .HasColumnName("source_type");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("WishlistItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("wishlist_item_id");

                    b.HasKey("Id")
                        .HasName("pk_gift_proposals");

                    b.HasIndex("SenderId", "CreatedAt")
                        .HasDatabaseName("ix_gift_proposals_sender_id_created_at");

                    b.HasIndex("RecipientId", "IsViewedByRecipient", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_gift_proposals_recipient_id_is_viewed_by_recipient_created_");

                    b.ToTable("gift_proposals", "proposals", t =>
                        {
                            t.HasCheckConstraint("ck_gift_proposals_source_type", "source_type IN (1, 2, 3)");

                            t.HasCheckConstraint("ck_gift_proposals_status", "status IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("Wishapp.Web.Reservations.Entities.WishReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ReservedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reserved_by_user_id");

                    b.Property<Guid>("WishId")
                        .HasColumnType("uuid")
                        .HasColumnName("wish_id");

                    b.Property<Guid>("WishlistId")
                        .HasColumnType("uuid")
                        .HasColumnName("wishlist_id");

                    b.HasKey("Id")
                        .HasName("pk_wish_reservations");

                    b.HasIndex("ReservedByUserId")
                        .HasDatabaseName("ix_wish_reservations_reserved_by_user_id");

                    b.HasIndex("WishId")
                        .IsUnique()
                        .HasDatabaseName("ix_wish_reservations_wish_id");

                    b.HasIndex("WishlistId")
                        .HasDatabaseName("ix_wish_reservations_wishlist_id");

                    b.ToTable("wish_reservations", "reservations");
                });

            modelBuilder.Entity("Wishapp.Web.Users.Entities.AuthIdentity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_auth_identities");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_auth_identities_user_id");

                    b.HasIndex("Provider", "ProviderKey")
                        .IsUnique()
                        .HasDatabaseName("ix_auth_identities_provider_provider_key");

                    b.ToTable("auth_identities", "users");
                });

            modelBuilder.Entity("Wishapp.Web.Users.Entities.BlacklistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_blacklist_items");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_blacklist_items_user_id");

                    b.ToTable("blacklist_items", "users", t =>
                        {
                            t.HasCheckConstraint("CK_blacklist_items_title_not_empty", "trim(title) <> ''");
                        });
                });

            modelBuilder.Entity("Wishapp.Web.Users.Entities.EmailOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("Id")
                        .HasName("pk_email_otps");

                    b.ToTable("email_otps", "users");
                });

            modelBuilder.Entity("Wishapp.Web.Users.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarPath")
                        .HasMaxLength(200)
                        .HasColumnType("text")
                        .HasColumnName("avatar_path");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsOnboarded")
                        .HasColumnType("boolean")
                        .HasColumnName("is_onboarded");

                    b.Property<bool>("ShowFulfilledWishes")
                        .HasColumnType("boolean")
                        .HasColumnName("show_fulfilled_wishes");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("DisplayName")
                        .HasDatabaseName("ix_users_display_name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("DisplayName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("DisplayName"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", "users", t =>
                        {
                            t.HasCheckConstraint("CK_users_display_name_not_empty", "trim(display_name) <> ''");

                            t.HasCheckConstraint("CK_users_email_not_empty", "trim(email) <> ''");

                            t.HasCheckConstraint("CK_users_username_not_empty", "username IS NULL OR trim(username) <> ''");
                        });
                });

            modelBuilder.Entity("Wishapp.Web.Users.Entities.UserExternalToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_external_tokens");

                    b.HasIndex("UserId", "Provider", "Scope")
                        .IsUnique()
                        .HasDatabaseName("ix_user_external_tokens_user_id_provider_scope");

                    b.ToTable("user_external_tokens", "users");
                });

            modelBuilder.Entity("Wishapp.Web.Users.Entities.UserRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("UserId", "TokenHash")
                        .HasDatabaseName("ix_refresh_tokens_user_id_token_hash");

                    b.ToTable("refresh_tokens", "users");
                });

            modelBuilder.Entity("Wishapp.Web.Wishlists.Entities.FulfilledWishRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset>("FulfilledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fulfilled_at");

                    b.Property<Guid?>("GifterId")
                        .HasColumnType("uuid")
                        .HasColumnName("gifter_id");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsFromHiddenWishlist")
                        .HasColumnType("boolean")
                        .HasColumnName("is_from_hidden_wishlist");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("WishDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("text")
                        .HasColumnName("wish_description");

                    b.Property<Guid>("WishId")
                        .HasColumnType("uuid")
                        .HasColumnName("wish_id");

                    b.Property<string>("WishName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("text")
                        .HasColumnName("wish_name");

                    b.Property<string>("WishlistName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("text")
                        .HasColumnName("wishlist_name");

                    b.HasKey("Id")
                        .HasName("pk_fulfilled_wish_records");

                    b.HasIndex("FulfilledAt")
                        .HasDatabaseName("ix_fulfilled_wish_records_fulfilled_at");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_fulfilled_wish_records_owner_id");

                    b.HasIndex("WishId")
                        .HasDatabaseName("ix_fulfilled_wish_records_wish_id");

                    b.ToTable("fulfilled_wish_records", "wishlists");
                });

            modelBuilder.Entity("Wishapp.Web.Wishlists.Entities.Wish", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Currency")
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("FulfilledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fulfilled_at");

                    b.Property<Guid?>("FulfilledByReserverId")
                        .HasColumnType("uuid")
                        .HasColumnName("fulfilled_by_reserver_id");

                    b.Property<Guid?>("FulfilledByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("fulfilled_by_user_id");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsFulfilled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fulfilled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<Guid>("ShareToken")
                        .HasColumnType("uuid")
                        .HasColumnName("share_token");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<Guid>("WishlistId")
                        .HasColumnType("uuid")
                        .HasColumnName("wishlist_id");

                    b.HasKey("Id")
                        .HasName("pk_wishes");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_wishes_created_at");

                    b.HasIndex("ShareToken")
                        .IsUnique()
                        .HasDatabaseName("ix_wishes_share_token");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_wishes_updated_at");

                    b.HasIndex("WishlistId")
                        .HasDatabaseName("ix_wishes_wishlist_id");

                    b.HasIndex("WishlistId", "CreatedAt")
                        .HasDatabaseName("ix_wishes_wishlist_id_created_at");

                    b.HasIndex("WishlistId", "IsFulfilled")
                        .HasDatabaseName("ix_wishes_wishlist_id_is_fulfilled");

                    b.HasIndex("WishlistId", "Name")
                        .HasDatabaseName("ix_wishes_wishlist_id_name");

                    b.HasIndex("WishlistId", "Priority")
                        .HasDatabaseName("ix_wishes_wishlist_id_priority");

                    b.ToTable("wishes", "wishlists", t =>
                        {
                            t.HasCheckConstraint("CK_wishes_name_not_empty", "trim(name) <> ''");

                            t.HasCheckConstraint("CK_wishes_price_positive", "price > 0");
                        });
                });

            modelBuilder.Entity("Wishapp.Web.Wishlists.Entities.Wishlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Emoji")
                        .HasMaxLength(10)
                        .HasColumnType("text")
                        .HasColumnName("emoji");

                    b.Property<bool>("IsSurpriseModeEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_surprise_mode_enabled");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_wishlists");

                    b.HasIndex("Visibility")
                        .HasDatabaseName("ix_wishlists_visibility");

                    b.HasIndex("OwnerId", "CreatedAt")
                        .HasDatabaseName("ix_wishlists_owner_id_created_at");

                    b.HasIndex("OwnerId", "Name")
                        .HasDatabaseName("ix_wishlists_owner_id_name");

                    b.ToTable("wishlists", "wishlists", t =>
                        {
                            t.HasCheckConstraint("CK_wishlists_name_not_empty", "trim(name) <> ''");
                        });
                });

            modelBuilder.Entity("Wishapp.Web.Wishlists.Entities.WishlistMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CustomRoleName")
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("custom_role_name");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WishlistId")
                        .HasColumnType("uuid")
                        .HasColumnName("wishlist_id");

                    b.HasKey("Id")
                        .HasName("pk_wishlist_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_wishlist_members_user_id");

                    b.HasIndex("WishlistId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_wishlist_members_wishlist_id_user_id");

                    b.ToTable("wishlist_members", "wishlists");
                });

            modelBuilder.Entity("Wishapp.Web.Catalog.Entities.CatalogCollection", b =>
                {
                    b.HasOne("Wishapp.Web.Catalog.Entities.CatalogOccasion", "Occasion")
                        .WithMany()
                        .HasForeignKey("OccasionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_catalog_collections_catalog_occasions_occasion_id");

                    b.Navigation("Occasion");
                });

            modelBuilder.Entity("Wishapp.Web.Catalog.Entities.CatalogCollectionItem", b =>
                {
                    b.HasOne("Wishapp.Web.Catalog.Entities.CatalogItem", "CatalogItem")
                        .WithMany()
                        .HasForeignKey("CatalogItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_collection_items_catalog_items_catalog_item_id");

                    b.HasOne("Wishapp.Web.Catalog.Entities.CatalogCollection", "Collection")
                        .WithMany("Items")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_collection_items_catalog_collections_collection_id");

                    b.Navigation("CatalogItem");

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("Wishapp.Web.Catalog.Entities.CatalogItem", b =>
                {
                    b.HasOne("Wishapp.Web.Catalog.Entities.CatalogCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_items_catalog_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Wishapp.Web.Catalog.Entities.CatalogItemOccasion", b =>
                {
                    b.HasOne("Wishapp.Web.Catalog.Entities.CatalogItem", "CatalogItem")
                        .WithMany("Occasions")
                        .HasForeignKey("CatalogItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_item_occasions_catalog_items_catalog_item_id");

                    b.HasOne("Wishapp.Web.Catalog.Entities.CatalogOccasion", "Occasion")
                        .WithMany()
                        .HasForeignKey("OccasionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_item_occasions_catalog_occasions_occasion_id");

                    b.Navigation("CatalogItem");

                    b.Navigation("Occasion");
                });

            modelBuilder.Entity("Wishapp.Web.Users.Entities.AuthIdentity", b =>
                {
                    b.HasOne("Wishapp.Web.Users.Entities.User", null)
                        .WithMany("Identities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_identities_users_user_id");
                });

            modelBuilder.Entity("Wishapp.Web.Wishlists.Entities.Wish", b =>
                {
                    b.HasOne("Wishapp.Web.Wishlists.Entities.Wishlist", null)
                        .WithMany("Wishes")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wishes_wishlists_wishlist_id");
                });

            modelBuilder.Entity("Wishapp.Web.Wishlists.Entities.WishlistMember", b =>
                {
                    b.HasOne("Wishapp.Web.Wishlists.Entities.Wishlist", null)
                        .WithMany("Members")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wishlist_members_wishlists_wishlist_id");
                });

            modelBuilder.Entity("Wishapp.Web.Catalog.Entities.CatalogCollection", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Wishapp.Web.Catalog.Entities.CatalogItem", b =>
                {
                    b.Navigation("Occasions");
                });

            modelBuilder.Entity("Wishapp.Web.Users.Entities.User", b =>
                {
                    b.Navigation("Identities");
                });

            modelBuilder.Entity("Wishapp.Web.Wishlists.Entities.Wishlist", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Wishes");
                });
#pragma warning restore 612, 618
        }
    }
}
