// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wishapp.Web.Infrastructure.Database;

#nullable disable

namespace Wishapp.Web.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260405111615_AddWishlistSurpriseMode")]
    partial class AddWishlistSurpriseMode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wishapp.Web.Admin.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_admin_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_admin_users_username");

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("Wishapp.Web.Catalog.Entities.CatalogCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.HasKey("Id")
                        .HasName("pk_catalog_categories");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_catalog_categories_name");

                    b.HasIndex("Order")
                        .HasDatabaseName("ix_catalog_categories_order");

                    b.ToTable("catalog_categories", null, t =>
                        {
                            t.HasCheckConstraint("CK_catalog_categories_name_not_empty", "trim(name) <> ''");

                            t.HasCheckConstraint("CK_catalog_categories_order_non_negative", "\"order\" >= 0");
                        });
                });

            modelBuilder.Entity("Wishapp.Web.Catalog.Entities.CatalogCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CoverImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("cover_image_path");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Occasion")
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("occasion");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.HasKey("Id")
                        .HasName("pk_catalog_collections");

                    b.HasIndex("IsPublished")
                        .HasDatabaseName("ix_catalog_collections_is_published");

                    b.HasIndex("Order")
                        .HasDatabaseName("ix_catalog_collections_order");

                    b.ToTable("catalog_collections", null, t =>
                        {
                            t.HasCheckConstraint("CK_catalog_collections_name_not_empty", "trim(name) <> ''");

                            t.HasCheckConstraint("CK_catalog_collections_order_non_negative", "\"order\" >= 0");
                        });
                });

            modelBuilder.Entity("Wishapp.Web.Catalog.Entities.CatalogCollectionItem", b =>
                {
                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<Guid>("CatalogItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_item_id");

                    b.HasKey("CollectionId", "CatalogItemId")
                        .HasName("pk_catalog_collection_items");

                    b.HasIndex("CatalogItemId")
                        .HasDatabaseName("ix_catalog_collection_items_catalog_item_id");

                    b.ToTable("catalog_collection_items", (string)null);
                });

            modelBuilder.Entity("Wishapp.Web.Catalog.Entities.CatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_catalog_items");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_catalog_items_category_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_catalog_items_created_at");

                    b.HasIndex("IsPublished")
                        .HasDatabaseName("ix_catalog_items_is_published");

                    b.ToTable("catalog_items", null, t =>
                        {
                            t.HasCheckConstraint("CK_catalog_items_name_not_empty", "trim(name) <> ''");

                            t.HasCheckConstraint("CK_catalog_items_price_positive", "price > 0");
                        });
                });

            modelBuilder.Entity("Wishapp.Web.Catalog.Entities.CatalogItemRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CatalogItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_item_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_catalog_item_ratings");

                    b.HasIndex("CatalogItemId")
                        .HasDatabaseName("ix_catalog_item_ratings_catalog_item_id");

                    b.HasIndex("UserId", "CatalogItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_catalog_item_ratings_user_id_catalog_item_id");

                    b.ToTable("catalog_item_ratings", null, t =>
                        {
                            t.HasCheckConstraint("CK_catalog_item_ratings_value", "value BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Wishapp.Web.Events.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("GoogleCalendarEventId")
                        .HasMaxLength(200)
                        .HasColumnType("text")
                        .HasColumnName("google_calendar_event_id");

                    b.Property<Guid?>("LinkedWishlistId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_wishlist_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_events_owner_id");

                    b.HasIndex("OwnerId", "Date")
                        .HasDatabaseName("ix_events_owner_id_date");

                    b.ToTable("events", null, t =>
                        {
                            t.HasCheckConstraint("CK_events_title_not_empty", "trim(title) <> ''");
                        });
                });

            modelBuilder.Entity("Wishapp.Web.Friendships.Entities.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AddresseeId")
                        .HasColumnType("uuid")
                        .HasColumnName("addressee_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_friendships");

                    b.HasIndex("AddresseeId")
                        .HasDatabaseName("ix_friendships_addressee_id");

                    b.HasIndex("RequesterId")
                        .HasDatabaseName("ix_friendships_requester_id");

                    b.HasIndex("RequesterId", "AddresseeId")
                        .IsUnique()
                        .HasDatabaseName("ix_friendships_requester_id_addressee_id");

                    b.ToTable("friendships", (string)null);
                });

            modelBuilder.Entity("Wishapp.Web.Reservations.Entities.WishReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ReservedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reserved_by_user_id");

                    b.Property<Guid>("WishId")
                        .HasColumnType("uuid")
                        .HasColumnName("wish_id");

                    b.Property<Guid>("WishlistId")
                        .HasColumnType("uuid")
                        .HasColumnName("wishlist_id");

                    b.HasKey("Id")
                        .HasName("pk_wish_reservations");

                    b.HasIndex("ReservedByUserId")
                        .HasDatabaseName("ix_wish_reservations_reserved_by_user_id");

                    b.HasIndex("WishId")
                        .IsUnique()
                        .HasDatabaseName("ix_wish_reservations_wish_id");

                    b.HasIndex("WishlistId")
                        .HasDatabaseName("ix_wish_reservations_wishlist_id");

                    b.ToTable("wish_reservations", (string)null);
                });

            modelBuilder.Entity("Wishapp.Web.Users.Entities.AuthIdentity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_auth_identities");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_auth_identities_user_id");

                    b.HasIndex("Provider", "ProviderKey")
                        .IsUnique()
                        .HasDatabaseName("ix_auth_identities_provider_provider_key");

                    b.ToTable("auth_identities", (string)null);
                });

            modelBuilder.Entity("Wishapp.Web.Users.Entities.EmailOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("Id")
                        .HasName("pk_email_otps");

                    b.ToTable("email_otps", (string)null);
                });

            modelBuilder.Entity("Wishapp.Web.Users.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsOnboarded")
                        .HasColumnType("boolean")
                        .HasColumnName("is_onboarded");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("CK_users_email_not_empty", "trim(email) <> ''");

                            t.HasCheckConstraint("CK_users_username_not_empty", "trim(username) <> ''");
                        });
                });

            modelBuilder.Entity("Wishapp.Web.Users.Entities.UserExternalToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_external_tokens");

                    b.HasIndex("UserId", "Provider", "Scope")
                        .IsUnique()
                        .HasDatabaseName("ix_user_external_tokens_user_id_provider_scope");

                    b.ToTable("user_external_tokens", (string)null);
                });

            modelBuilder.Entity("Wishapp.Web.Users.Entities.UserRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("UserId", "TokenHash")
                        .HasDatabaseName("ix_refresh_tokens_user_id_token_hash");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Wishapp.Web.Wishlists.Entities.Wish", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("FulfilledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fulfilled_at");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsFulfilled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fulfilled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<Guid>("ShareToken")
                        .HasColumnType("uuid")
                        .HasColumnName("share_token");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<Guid>("WishlistId")
                        .HasColumnType("uuid")
                        .HasColumnName("wishlist_id");

                    b.HasKey("Id")
                        .HasName("pk_wishes");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_wishes_created_at");

                    b.HasIndex("ShareToken")
                        .IsUnique()
                        .HasDatabaseName("ix_wishes_share_token");

                    b.HasIndex("WishlistId")
                        .HasDatabaseName("ix_wishes_wishlist_id");

                    b.ToTable("wishes", null, t =>
                        {
                            t.HasCheckConstraint("CK_wishes_name_not_empty", "trim(name) <> ''");

                            t.HasCheckConstraint("CK_wishes_price_positive", "price > 0");
                        });
                });

            modelBuilder.Entity("Wishapp.Web.Wishlists.Entities.Wishlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Emoji")
                        .HasMaxLength(10)
                        .HasColumnType("text")
                        .HasColumnName("emoji");

                    b.Property<bool>("IsSurpriseModeEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_surprise_mode_enabled");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_wishlists");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_wishlists_created_at");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_wishlists_owner_id");

                    b.HasIndex("Visibility")
                        .HasDatabaseName("ix_wishlists_visibility");

                    b.ToTable("wishlists", null, t =>
                        {
                            t.HasCheckConstraint("CK_wishlists_name_not_empty", "trim(name) <> ''");
                        });
                });

            modelBuilder.Entity("Wishapp.Web.Wishlists.Entities.WishlistMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CustomRoleName")
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("custom_role_name");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WishlistId")
                        .HasColumnType("uuid")
                        .HasColumnName("wishlist_id");

                    b.HasKey("Id")
                        .HasName("pk_wishlist_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_wishlist_members_user_id");

                    b.HasIndex("WishlistId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_wishlist_members_wishlist_id_user_id");

                    b.ToTable("wishlist_members", (string)null);
                });

            modelBuilder.Entity("Wishapp.Web.Catalog.Entities.CatalogCollectionItem", b =>
                {
                    b.HasOne("Wishapp.Web.Catalog.Entities.CatalogItem", "CatalogItem")
                        .WithMany()
                        .HasForeignKey("CatalogItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_collection_items_catalog_items_catalog_item_id");

                    b.HasOne("Wishapp.Web.Catalog.Entities.CatalogCollection", "Collection")
                        .WithMany("Items")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_collection_items_catalog_collections_collection_id");

                    b.Navigation("CatalogItem");

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("Wishapp.Web.Catalog.Entities.CatalogItem", b =>
                {
                    b.HasOne("Wishapp.Web.Catalog.Entities.CatalogCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_items_catalog_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Wishapp.Web.Catalog.Entities.CatalogItemRating", b =>
                {
                    b.HasOne("Wishapp.Web.Catalog.Entities.CatalogItem", null)
                        .WithMany("Ratings")
                        .HasForeignKey("CatalogItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_item_ratings_catalog_items_catalog_item_id");
                });

            modelBuilder.Entity("Wishapp.Web.Users.Entities.AuthIdentity", b =>
                {
                    b.HasOne("Wishapp.Web.Users.Entities.User", null)
                        .WithMany("Identities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_identities_users_user_id");
                });

            modelBuilder.Entity("Wishapp.Web.Wishlists.Entities.Wish", b =>
                {
                    b.HasOne("Wishapp.Web.Wishlists.Entities.Wishlist", null)
                        .WithMany("Wishes")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wishes_wishlists_wishlist_id");
                });

            modelBuilder.Entity("Wishapp.Web.Wishlists.Entities.WishlistMember", b =>
                {
                    b.HasOne("Wishapp.Web.Wishlists.Entities.Wishlist", null)
                        .WithMany("Members")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wishlist_members_wishlists_wishlist_id");
                });

            modelBuilder.Entity("Wishapp.Web.Catalog.Entities.CatalogCollection", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Wishapp.Web.Catalog.Entities.CatalogItem", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("Wishapp.Web.Users.Entities.User", b =>
                {
                    b.Navigation("Identities");
                });

            modelBuilder.Entity("Wishapp.Web.Wishlists.Entities.Wishlist", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Wishes");
                });
#pragma warning restore 612, 618
        }
    }
}
