listen_addresses = '*'
max_connections = 100
shared_buffers = 4096MB
work_mem = 32MB
maintenance_work_mem = 128MB

effective_cache_size = 1024MB
random_page_cost = 1.1

wal_level = replica
max_wal_size = 1GB
min_wal_size = 80MB
