listen_addresses = '*'
max_connections = 100
shared_buffers = 256MB
work_mem = 16MB
maintenance_work_mem = 64MB

effective_cache_size = 1GB
random_page_cost = 1.1

wal_level = replica
max_wal_size = 1GB
min_wal_size = 80MB
